apiVersion: v1
kind: Service
metadata:
  name: orders-api-service
  namespace: canary-orders
  labels:
    app: orders-api
    environment: dev
    strategy: canary
spec:
  type: NodePort
  selector:
    app: orders-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30090