apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api-canary
  namespace: canary-orders
  labels:
    app: orders-api
    environment: dev
    strategy: canary
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
      track: canary
  template:
    metadata:
      labels:
        app: orders-api
        environment: dev
        strategy: canary
        track: canary
    spec:
      containers:
        - name: orders-api
          image: httpd:2.4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3