apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-green
  namespace: lab32
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-api
      slot: green
  template:
    metadata:
      labels:
        app: demo-api
        slot: green
    spec:
      containers:
        - name: api
          image: asanchezoduoc/demo-api:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /ruta-que-no-existe
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2
