name: EFT - Deploy estrategia Canary en k8s

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests
        run: npm ci && npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/demo-api:latest
            ${{ secrets.DOCKER_USERNAME }}/demo-api:${{ github.sha }}

  deploy-canary:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.K3S_SERVER_PUBLIC_IP }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EA2_SSH_PRIVATE_KEY }}

      - name: Copy Canary manifest to k3s server
        run: |
          scp -o StrictHostKeyChecking=accept-new \
            k8s/canary-namespace.yaml \
            k8s/canary-stable-deployment.yaml \
            k8s/canary-deployment.yaml \
            k8s/canary-service.yaml \
            ubuntu@${SERVER_IP}:/tmp/

      - name: Deploy Canary stack to K3s
        run: |
          ssh -o StrictHostKeyChecking=accept-new ubuntu@${SERVER_IP} << 'EOF'
          set -e
          #Implementar manifiestos
          sudo k3s kubectl apply -f /tmp/canary-namespace.yaml
          sudo k3s kubectl apply -f /tmp/canary-stable-deployment.yaml
          sudo k3s kubectl apply -f /tmp/canary-deployment.yaml
          sudo k3s kubectl apply -f /tmp/canary-service.yaml
          
          #Validar funcionamiento
          sudo k3s kubectl get deployments -n canary-orders
          sudo k3s kubectl get pods -n canary-orders --show-labels
          sudo k3s kubectl get svc -n canary-orders
          EOF

      - name: Verify /health endpoint
        run: |
          sleep 10
          curl -f http://${SERVER_IP}:30080