name: EFT - Pipeline Canary completo

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: canary-orders-deployment
  cancel-in-progress: false

jobs:
  build:
    uses: AUY1104-SDLC-II/devops-library/.github/workflows/eft-docker-deploy.yaml@main
    secrets: inherit

  deploy:
    needs: build
    uses: AUY1104-SDLC-II/devops-library/.github/workflows/eft-canary-deploy.yaml@main
    with:
      stable_image: mafernandezz/auy1104-app@sha256:8cf9ad3c7a1ae510034a85eaa00107edf167ac785e29165e8f5985581c5c59b4
      server_ip: ${{ vars.K3S_SERVER_PUBLIC_IP }}
      image_name: auy1104-app
    secrets: inherit