name: Client Test Execution

on:
  push:
    branches:
      - feature/*
    tags-ignore:
      - "**"

jobs:
  validate-and-build:
    uses: AUY1104-SDLC-II/devops-library/.github/workflows/deploy-api.yaml@feat/logic-validation
    with:
      image_name: "auy1104-app"
      image_tag: ${{ github.sha }}
      push_image: false
    secrets: inherit